site_name: Progression STI2D
site_url: https://lidlkidjoe.github.io/Progression-STI2D-2025/

theme:
  name: material
  features:
    - content.code.copy
  language: fr
  font:
    text: Raleway
    code: Roboto Mono
  logo: assets/logosti2d.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: deep purple
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue
      accent: deep orange

nav:
  - STI2D: index.md
  - Bienvenue:
      - Accueil: accueil.md
      - Idées et faits importants: faits.md
      - Citations: citations.md
      - Implications: implications.md
  - Première:
    - Introduction: premiere.md
    - Maison positive: premiere_maison.md
    - Bras manipulateur: premiere_bras.md
    - Robobrole: premiere_robobrole.md
    - Mobilité: premiere_mobilite.md
    - Compétences: premiere_competence.md
  - Terminale: Terminale.md
  - Ressources: Ressources.md

markdown_extensions:
  - markdown.extensions.abbr
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - pymdownx.highlight:
      linenums: true  # Active les numéros de ligne (facultatif)
  - codehilite:
      guess_lang: false  # Désactive la détection automatique du langage
      linenums: true     # Active les numéros de ligne (facultatif)
  - pymdownx.superfences
  - pymdownx.highlight

extra_javascript:
  - js/firebase.js
      